alias be='bundle exec'
alias bi='bundle install'

alias g='git'
alias gcm='git checkout master'
alias gco='git checkout'
alias gp='git push'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gs='git status -sb'
alias gd='git diff'
alias commit='git commit -a -m'
alias hist='history 1'
alias rc='bundle exec rails console'
alias rs='bundle exec rails s -p5500'
alias test='bundle exec rspec'
